/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as PlayCategoryIndexRouteImport } from './routes/play.$category.index'
import { Route as PlayCategoryLevelRouteImport } from './routes/play.$category.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategoryIndexRoute = PlayCategoryIndexRouteImport.update({
  id: '/play/$category/',
  path: '/play/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategoryLevelRoute = PlayCategoryLevelRouteImport.update({
  id: '/play/$category/$level',
  path: '/play/$category/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/stars': typeof StarsRoute
  '/play/$category/$level': typeof PlayCategoryLevelRoute
  '/play/$category/': typeof PlayCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/stars': typeof StarsRoute
  '/play/$category/$level': typeof PlayCategoryLevelRoute
  '/play/$category': typeof PlayCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/stars': typeof StarsRoute
  '/play/$category/$level': typeof PlayCategoryLevelRoute
  '/play/$category/': typeof PlayCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/parents'
    | '/privacy'
    | '/stars'
    | '/play/$category/$level'
    | '/play/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/parents'
    | '/privacy'
    | '/stars'
    | '/play/$category/$level'
    | '/play/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/parents'
    | '/privacy'
    | '/stars'
    | '/play/$category/$level'
    | '/play/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ParentsRoute: typeof ParentsRoute
  PrivacyRoute: typeof PrivacyRoute
  StarsRoute: typeof StarsRoute
  PlayCategoryLevelRoute: typeof PlayCategoryLevelRoute
  PlayCategoryIndexRoute: typeof PlayCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category/': {
      id: '/play/$category/'
      path: '/play/$category'
      fullPath: '/play/$category/'
      preLoaderRoute: typeof PlayCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category/$level': {
      id: '/play/$category/$level'
      path: '/play/$category/$level'
      fullPath: '/play/$category/$level'
      preLoaderRoute: typeof PlayCategoryLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ParentsRoute: ParentsRoute,
  PrivacyRoute: PrivacyRoute,
  StarsRoute: StarsRoute,
  PlayCategoryLevelRoute: PlayCategoryLevelRoute,
  PlayCategoryIndexRoute: PlayCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
